@{
    # PSScriptAnalyzer configuration for WinForge
    # https://github.com/PowerShell/PSScriptAnalyzer
    #
    # This file deliberately does NOT declare IncludeRules. IncludeRules is an allowlist:
    # declaring it means only the listed rules ever run, and any rule added to
    # PSScriptAnalyzer later is silently ignored. The previous configuration combined an
    # IncludeRules allowlist with an ExcludeRules list that cancelled 21 of the rules it
    # had just enabled, and then configured 6 rules that were themselves excluded. The
    # effective gate could not fail.
    #
    # The full default rule set now runs. Every entry in ExcludeRules below states why it
    # is suppressed; anything not listed here is expected to stay clean.
    #
    # Expected steady state: 0 errors (errors fail the build) and 7 warnings, all of which
    # are deliberate and left visible rather than suppressed:
    #   - PSAvoidDefaultValueSwitchParameter x4 - -AutoLoad / -CreateBackup /
    #     -IncludeMetadata / -RemoveDuplicates are on by default by design; callers opt out
    #     with -Switch:$false. Changing the defaults would change behaviour.
    #   - PSAvoidUsingBrokenHashAlgorithms x2 - Core.Tests.ps1 asserts that Get-StringHash
    #     still supports MD5 and SHA1 for legacy comparisons.
    #   - PSAvoidUsingInvokeExpression x1 - RestApiServer.Tests.ps1 feeds an
    #     Invoke-Expression handler to the endpoint validator to prove it is rejected.
    # Suppressing these repo-wide would also hide a genuine future occurrence in
    # production code, so they stay reported.

    # === SEVERITY ===
    Severity = @('Error', 'Warning', 'Information')

    # === EXCLUDE RULES ===
    ExcludeRules = @(
        # Write-Host is the intended output mechanism for the console-facing scripts
        # (Deploy-Win11Environment.ps1, Build-Release.ps1, the Tools/* validators). Their
        # output is a UI, not a pipeline contract.
        'PSAvoidUsingWriteHost',

        # Plural nouns are used where the command genuinely acts on a collection
        # (Get-AvailablePlugins, Get-ApiKeys). Renaming them would break the public
        # module surface for no behavioural gain.
        'PSUseSingularNouns',

        # -WhatIf/-Confirm support across the state-changing surface (Set-* in
        # SystemConfig, Start-*, Update-*, New-*, Reset-*) is a deliberate, tracked
        # enhancement rather than a defect. Enabling the rule today would report ~70
        # findings with no fix in this pass.
        'PSUseShouldProcessForStateChangingFunctions',
        'PSUseSupportsShouldProcess',

        # Positional parameters are used inside private helpers for brevity; call sites
        # are local and covered by tests.
        'PSAvoidUsingPositionalParameters',

        # Comment-based help is present throughout but does not always match the strict
        # shape this rule expects (for example .OUTPUTS without a type name).
        'PSProvideCommentHelp',

        # Several handlers accept parameters they do not read in order to satisfy a shared
        # signature (hook handlers, detection strategies). The unused parameter is the
        # interface contract.
        'PSReviewUnusedParameter',

        # False positive for this codebase: the flagged scriptblocks are passed to
        # Start-Job with an explicit param() block and -ArgumentList, which is the correct
        # way to marshal values into a new runspace. $using: would be wrong there.
        'PSUseUsingScopeModifierInNewRunspaces',

        # The manifests are generated by Tools/Generate-ModuleManifests.ps1. Replacing the
        # wildcard exports with explicit lists belongs to that generator, not to hand
        # edits that would be overwritten on the next run.
        'PSUseToExportFieldsInManifest',

        # Formatting is enforced by .editorconfig and EnforceCodeStyleInBuild rather than
        # by the analyzer, so these would duplicate an existing gate.
        'PSPlaceCloseBrace',
        'PSPlaceOpenBrace',
        'PSUseConsistentIndentation',
        'PSUseConsistentWhitespace',
        'PSUseCorrectCasing',

        # [OutputType] is documentation here; several functions legitimately return
        # different shapes depending on the failure path.
        'PSUseOutputTypeCorrectly',

        # 8.8.8.8 is hardcoded on purpose as the internet-connectivity probe target.
        'PSAvoidUsingComputerNameHardcoded',

        # Write-Log is the project's own logging function, not the built-in cmdlet the
        # rule is guarding.
        'PSAvoidOverwritingBuiltInCmdlets'
    )

    # === CODE FORMATTING ===
    # Only rules that actually run are configured here. Formatting rules are excluded
    # above and therefore carry no configuration block.
    Rules = @{
        # Cmdlet aliases
        PSAvoidUsingCmdletAliases = @{
            Enable = $true
        }

        # Compatible syntax (PowerShell 5.1+)
        PSUseCompatibleSyntax = @{
            Enable = $true
            TargetVersions = @(
                '5.1',
                '7.0',
                '7.1',
                '7.2',
                '7.3',
                '7.4'
            )
        }

        # Compatible cmdlets
        PSUseCompatibleCmdlets = @{
            Enable = $true
            Compatibility = @(
                'desktop-5.1.14393.206-windows',
                'core-7.4.0-windows'
            )
        }
    }
}
