//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win11Forge.GUI.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;
    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() { }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win11Forge.GUI.Resources.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get { return resourceCulture; }
        set { resourceCulture = value; }
    }

    // Application
    public static string App_Title => ResourceManager.GetString("App_Title", resourceCulture);

    // Main Window
    public static string MainWindow_Welcome => ResourceManager.GetString("MainWindow_Welcome", resourceCulture);

    // Dashboard
    public static string Dashboard_Title => ResourceManager.GetString("Dashboard_Title", resourceCulture);
    public static string Dashboard_Version_Prefix => ResourceManager.GetString("Dashboard_Version_Prefix", resourceCulture);
    public static string Dashboard_Repository_Prefix => ResourceManager.GetString("Dashboard_Repository_Prefix", resourceCulture);
    public static string Dashboard_SystemInfo_Title => ResourceManager.GetString("Dashboard_SystemInfo_Title", resourceCulture);

    // Deployment
    public static string Deploy_Title => ResourceManager.GetString("Deploy_Title", resourceCulture);
    public static string Deploy_SelectProfile => ResourceManager.GetString("Deploy_SelectProfile", resourceCulture);
    public static string Deploy_ProfileSummary => ResourceManager.GetString("Deploy_ProfileSummary", resourceCulture);
    public static string Deploy_Applications => ResourceManager.GetString("Deploy_Applications", resourceCulture);
    public static string Deploy_TotalApps => ResourceManager.GetString("Deploy_TotalApps", resourceCulture);
    public static string Deploy_RequiredApps => ResourceManager.GetString("Deploy_RequiredApps", resourceCulture);
    public static string Deploy_InheritedFrom => ResourceManager.GetString("Deploy_InheritedFrom", resourceCulture);
    public static string Deploy_SelectAll => ResourceManager.GetString("Deploy_SelectAll", resourceCulture);
    public static string Deploy_SelectNone => ResourceManager.GetString("Deploy_SelectNone", resourceCulture);
    public static string Deploy_Selected => ResourceManager.GetString("Deploy_Selected", resourceCulture);

    // Column Headers
    public static string Col_Status => ResourceManager.GetString("Col_Status", resourceCulture);
    public static string Col_Application => ResourceManager.GetString("Col_Application", resourceCulture);
    public static string Col_Category => ResourceManager.GetString("Col_Category", resourceCulture);
    public static string Col_Priority => ResourceManager.GetString("Col_Priority", resourceCulture);
    public static string Col_Required => ResourceManager.GetString("Col_Required", resourceCulture);

    // Common
    public static string Common_Loading => ResourceManager.GetString("Common_Loading", resourceCulture);
    public static string Common_Error => ResourceManager.GetString("Common_Error", resourceCulture);

    // Navigation
    public static string Nav_Dashboard => ResourceManager.GetString("Nav_Dashboard", resourceCulture);
    public static string Nav_Deployment => ResourceManager.GetString("Nav_Deployment", resourceCulture);
    public static string Nav_Apps => ResourceManager.GetString("Nav_Apps", resourceCulture);

    // Application Manager
    public static string Apps_Title => ResourceManager.GetString("Apps_Title", resourceCulture);
    public static string Apps_SearchHint => ResourceManager.GetString("Apps_SearchHint", resourceCulture);
    public static string Apps_CategoryAll => ResourceManager.GetString("Apps_CategoryAll", resourceCulture);
    public static string Apps_ClearFilters => ResourceManager.GetString("Apps_ClearFilters", resourceCulture);
    public static string Apps_Col_Sources => ResourceManager.GetString("Apps_Col_Sources", resourceCulture);
    public static string Apps_Col_Id => ResourceManager.GetString("Apps_Col_Id", resourceCulture);
    public static string Btn_Scan => ResourceManager.GetString("Btn_Scan", resourceCulture);
    public static string Btn_Install => ResourceManager.GetString("Btn_Install", resourceCulture);
    public static string Col_Actions => ResourceManager.GetString("Col_Actions", resourceCulture);
    public static string Status_Checking => ResourceManager.GetString("Status_Checking", resourceCulture);
    public static string Status_Missing => ResourceManager.GetString("Status_Missing", resourceCulture);

    // Deployment Execution
    public static string Btn_Deploy => ResourceManager.GetString("Btn_Deploy", resourceCulture);
    public static string Btn_Cancel => ResourceManager.GetString("Btn_Cancel", resourceCulture);
    public static string Btn_Pause => ResourceManager.GetString("Btn_Pause", resourceCulture);
    public static string Btn_Resume => ResourceManager.GetString("Btn_Resume", resourceCulture);
    public static string Lbl_DryRun => ResourceManager.GetString("Lbl_DryRun", resourceCulture);
    public static string Lbl_DryRun_Hint => ResourceManager.GetString("Lbl_DryRun_Hint", resourceCulture);

    // Status Messages
    public static string Status_Pending => ResourceManager.GetString("Status_Pending", resourceCulture);
    public static string Status_Installing => ResourceManager.GetString("Status_Installing", resourceCulture);
    public static string Status_Installed => ResourceManager.GetString("Status_Installed", resourceCulture);
    public static string Status_Failed => ResourceManager.GetString("Status_Failed", resourceCulture);
    public static string Status_Skipped => ResourceManager.GetString("Status_Skipped", resourceCulture);
    public static string Status_AlreadyInstalled => ResourceManager.GetString("Status_AlreadyInstalled", resourceCulture);
    public static string Status_Paused => ResourceManager.GetString("Status_Paused", resourceCulture);

    // Progress
    public static string Progress_Installing => ResourceManager.GetString("Progress_Installing", resourceCulture);
    public static string Progress_Complete => ResourceManager.GetString("Progress_Complete", resourceCulture);
    public static string Progress_Cancelled => ResourceManager.GetString("Progress_Cancelled", resourceCulture);
    public static string Progress_Deploying => ResourceManager.GetString("Progress_Deploying", resourceCulture);

    // Profile Editor
    public static string Nav_ProfileEditor => ResourceManager.GetString("Nav_ProfileEditor", resourceCulture);
    public static string Editor_Title_New => ResourceManager.GetString("Editor_Title_New", resourceCulture);
    public static string Editor_Title_Edit => ResourceManager.GetString("Editor_Title_Edit", resourceCulture);
    public static string Editor_Lbl_Name => ResourceManager.GetString("Editor_Lbl_Name", resourceCulture);
    public static string Editor_Lbl_Parent => ResourceManager.GetString("Editor_Lbl_Parent", resourceCulture);
    public static string Editor_Lbl_Description => ResourceManager.GetString("Editor_Lbl_Description", resourceCulture);
    public static string Editor_Section_Inherited => ResourceManager.GetString("Editor_Section_Inherited", resourceCulture);
    public static string Editor_Section_Added => ResourceManager.GetString("Editor_Section_Added", resourceCulture);
    public static string Editor_NoParent => ResourceManager.GetString("Editor_NoParent", resourceCulture);
    public static string Editor_Empty_NoParent => ResourceManager.GetString("Editor_Empty_NoParent", resourceCulture);
    public static string Editor_Empty_NoApps => ResourceManager.GetString("Editor_Empty_NoApps", resourceCulture);
    public static string Editor_Tooltip_Inherited => ResourceManager.GetString("Editor_Tooltip_Inherited", resourceCulture);
    public static string Editor_Tooltip_Add => ResourceManager.GetString("Editor_Tooltip_Add", resourceCulture);
    public static string Editor_Tooltip_Remove => ResourceManager.GetString("Editor_Tooltip_Remove", resourceCulture);
    public static string Editor_Error_NameRequired => ResourceManager.GetString("Editor_Error_NameRequired", resourceCulture);
    public static string Editor_Error_LoadParent => ResourceManager.GetString("Editor_Error_LoadParent", resourceCulture);
    public static string Editor_Error_InvalidName => ResourceManager.GetString("Editor_Error_InvalidName", resourceCulture);
    public static string Editor_Error_SaveFailed => ResourceManager.GetString("Editor_Error_SaveFailed", resourceCulture);
    public static string Btn_Save => ResourceManager.GetString("Btn_Save", resourceCulture);
    public static string Msg_ProfileSaved => ResourceManager.GetString("Msg_ProfileSaved", resourceCulture);

    // Application Picker Dialog
    public static string Dialog_SelectApp_Title => ResourceManager.GetString("Dialog_SelectApp_Title", resourceCulture);
    public static string Dialog_SelectApp_Add => ResourceManager.GetString("Dialog_SelectApp_Add", resourceCulture);
    public static string Dialog_NoAppsAvailable => ResourceManager.GetString("Dialog_NoAppsAvailable", resourceCulture);
    public static string Dialog_AppsAvailable => ResourceManager.GetString("Dialog_AppsAvailable", resourceCulture);

    // Dashboard - Extended
    public static string Dashboard_Refresh => ResourceManager.GetString("Dashboard_Refresh", resourceCulture);
    public static string Dashboard_Stat_Profiles => ResourceManager.GetString("Dashboard_Stat_Profiles", resourceCulture);
    public static string Dashboard_Stat_Apps => ResourceManager.GetString("Dashboard_Stat_Apps", resourceCulture);
    public static string Dashboard_Stat_Deployments => ResourceManager.GetString("Dashboard_Stat_Deployments", resourceCulture);
    public static string Dashboard_Stat_Version => ResourceManager.GetString("Dashboard_Stat_Version", resourceCulture);
    public static string Dashboard_Sys_Hostname => ResourceManager.GetString("Dashboard_Sys_Hostname", resourceCulture);
    public static string Dashboard_Sys_OS => ResourceManager.GetString("Dashboard_Sys_OS", resourceCulture);
    public static string Dashboard_Sys_Build => ResourceManager.GetString("Dashboard_Sys_Build", resourceCulture);
    public static string Dashboard_Sys_Admin => ResourceManager.GetString("Dashboard_Sys_Admin", resourceCulture);
    public static string Dashboard_RecentActivity => ResourceManager.GetString("Dashboard_RecentActivity", resourceCulture);
    public static string Dashboard_NoActivity => ResourceManager.GetString("Dashboard_NoActivity", resourceCulture);

    // Settings
    public static string Nav_Settings => ResourceManager.GetString("Nav_Settings", resourceCulture);
    public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture);
    public static string Settings_Section_Appearance => ResourceManager.GetString("Settings_Section_Appearance", resourceCulture);
    public static string Settings_Section_Language => ResourceManager.GetString("Settings_Section_Language", resourceCulture);
    public static string Settings_Section_Data => ResourceManager.GetString("Settings_Section_Data", resourceCulture);
    public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture);
    public static string Settings_Theme_Desc => ResourceManager.GetString("Settings_Theme_Desc", resourceCulture);
    public static string Settings_ThemeApplied => ResourceManager.GetString("Settings_ThemeApplied", resourceCulture);
    public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture);
    public static string Settings_Language_Desc => ResourceManager.GetString("Settings_Language_Desc", resourceCulture);
    public static string Settings_Apply => ResourceManager.GetString("Settings_Apply", resourceCulture);
    public static string Settings_RestartRequired => ResourceManager.GetString("Settings_RestartRequired", resourceCulture);
    public static string Settings_ClearHistory => ResourceManager.GetString("Settings_ClearHistory", resourceCulture);
    public static string Settings_ClearHistory_Desc => ResourceManager.GetString("Settings_ClearHistory_Desc", resourceCulture);
    public static string Settings_ClearBtn => ResourceManager.GetString("Settings_ClearBtn", resourceCulture);
    public static string Settings_HistoryCleared => ResourceManager.GetString("Settings_HistoryCleared", resourceCulture);

    // Package Managers
    public static string Dashboard_Sys_Winget => ResourceManager.GetString("Dashboard_Sys_Winget", resourceCulture);
    public static string Dashboard_Sys_Chocolatey => ResourceManager.GetString("Dashboard_Sys_Chocolatey", resourceCulture);

    // Apps Manager - Extended
    public static string Apps_Installed => ResourceManager.GetString("Apps_Installed", resourceCulture);

    // Error Messages
    public static string Common_ErrorFallback => ResourceManager.GetString("Common_ErrorFallback", resourceCulture);
}
