//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Win11Forge.GUI.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources
{
    private static global::System.Resources.ResourceManager resourceMan;
    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() { }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Win11Forge.GUI.Resources.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get { return resourceCulture; }
        set { resourceCulture = value; }
    }

    // Application
    public static string App_Title => ResourceManager.GetString("App_Title", resourceCulture);

    // Main Window
    public static string MainWindow_Welcome => ResourceManager.GetString("MainWindow_Welcome", resourceCulture);

    // Dashboard
    public static string Dashboard_Title => ResourceManager.GetString("Dashboard_Title", resourceCulture);
    public static string Dashboard_Version_Prefix => ResourceManager.GetString("Dashboard_Version_Prefix", resourceCulture);
    public static string Dashboard_Repository_Prefix => ResourceManager.GetString("Dashboard_Repository_Prefix", resourceCulture);
    public static string Dashboard_SystemInfo_Title => ResourceManager.GetString("Dashboard_SystemInfo_Title", resourceCulture);

    // Deployment
    public static string Deploy_Title => ResourceManager.GetString("Deploy_Title", resourceCulture);

    // Breadcrumb Steps
    public static string Breadcrumb_SelectProfile => ResourceManager.GetString("Breadcrumb_SelectProfile", resourceCulture);
    public static string Breadcrumb_Configure => ResourceManager.GetString("Breadcrumb_Configure", resourceCulture);
    public static string Breadcrumb_Deploy => ResourceManager.GetString("Breadcrumb_Deploy", resourceCulture);

    public static string Deploy_SelectProfile => ResourceManager.GetString("Deploy_SelectProfile", resourceCulture);
    public static string Deploy_ProfileSummary => ResourceManager.GetString("Deploy_ProfileSummary", resourceCulture);
    public static string Deploy_Applications => ResourceManager.GetString("Deploy_Applications", resourceCulture);
    public static string Deploy_TotalApps => ResourceManager.GetString("Deploy_TotalApps", resourceCulture);
    public static string Deploy_RequiredApps => ResourceManager.GetString("Deploy_RequiredApps", resourceCulture);
    public static string Deploy_InheritedFrom => ResourceManager.GetString("Deploy_InheritedFrom", resourceCulture);
    public static string Deploy_SelectAll => ResourceManager.GetString("Deploy_SelectAll", resourceCulture);
    public static string Deploy_SelectNone => ResourceManager.GetString("Deploy_SelectNone", resourceCulture);
    public static string Deploy_Selected => ResourceManager.GetString("Deploy_Selected", resourceCulture);

    // Column Headers
    public static string Col_Status => ResourceManager.GetString("Col_Status", resourceCulture);
    public static string Col_Application => ResourceManager.GetString("Col_Application", resourceCulture);
    public static string Col_Category => ResourceManager.GetString("Col_Category", resourceCulture);
    public static string Col_Priority => ResourceManager.GetString("Col_Priority", resourceCulture);
    public static string Col_Required => ResourceManager.GetString("Col_Required", resourceCulture);

    // Common
    public static string Common_Loading => ResourceManager.GetString("Common_Loading", resourceCulture);
    public static string Common_Error => ResourceManager.GetString("Common_Error", resourceCulture);
    public static string Common_Yes => ResourceManager.GetString("Common_Yes", resourceCulture);
    public static string Common_No => ResourceManager.GetString("Common_No", resourceCulture);
    public static string Common_Unknown => ResourceManager.GetString("Common_Unknown", resourceCulture);

    // Navigation
    public static string Nav_Dashboard => ResourceManager.GetString("Nav_Dashboard", resourceCulture);
    public static string Nav_Deployment => ResourceManager.GetString("Nav_Deployment", resourceCulture);
    public static string Nav_Apps => ResourceManager.GetString("Nav_Apps", resourceCulture);

    // Application Manager
    public static string Apps_Title => ResourceManager.GetString("Apps_Title", resourceCulture);
    public static string Apps_SearchHint => ResourceManager.GetString("Apps_SearchHint", resourceCulture);
    public static string Search_RecentSearches => ResourceManager.GetString("Search_RecentSearches", resourceCulture);
    public static string Apps_CategoryAll => ResourceManager.GetString("Apps_CategoryAll", resourceCulture);
    public static string Apps_ClearFilters => ResourceManager.GetString("Apps_ClearFilters", resourceCulture);
    public static string Apps_Col_Sources => ResourceManager.GetString("Apps_Col_Sources", resourceCulture);
    public static string Apps_Col_Id => ResourceManager.GetString("Apps_Col_Id", resourceCulture);
    public static string Btn_Scan => ResourceManager.GetString("Btn_Scan", resourceCulture);
    public static string Btn_Install => ResourceManager.GetString("Btn_Install", resourceCulture);
    public static string Col_Actions => ResourceManager.GetString("Col_Actions", resourceCulture);
    public static string Status_Checking => ResourceManager.GetString("Status_Checking", resourceCulture);
    public static string Status_Missing => ResourceManager.GetString("Status_Missing", resourceCulture);

    // Deployment Execution
    public static string Btn_Deploy => ResourceManager.GetString("Btn_Deploy", resourceCulture);
    public static string Btn_Cancel => ResourceManager.GetString("Btn_Cancel", resourceCulture);
    public static string Btn_Pause => ResourceManager.GetString("Btn_Pause", resourceCulture);
    public static string Btn_Resume => ResourceManager.GetString("Btn_Resume", resourceCulture);
    public static string Lbl_DryRun => ResourceManager.GetString("Lbl_DryRun", resourceCulture);
    public static string Lbl_DryRun_Hint => ResourceManager.GetString("Lbl_DryRun_Hint", resourceCulture);

    // Status Messages
    public static string Status_Pending => ResourceManager.GetString("Status_Pending", resourceCulture);
    public static string Status_Installing => ResourceManager.GetString("Status_Installing", resourceCulture);
    public static string Status_Installed => ResourceManager.GetString("Status_Installed", resourceCulture);
    public static string Status_Failed => ResourceManager.GetString("Status_Failed", resourceCulture);
    public static string Status_Skipped => ResourceManager.GetString("Status_Skipped", resourceCulture);
    public static string Status_AlreadyInstalled => ResourceManager.GetString("Status_AlreadyInstalled", resourceCulture);
    public static string Status_Paused => ResourceManager.GetString("Status_Paused", resourceCulture);

    // Progress
    public static string Progress_Installing => ResourceManager.GetString("Progress_Installing", resourceCulture);
    public static string Progress_Complete => ResourceManager.GetString("Progress_Complete", resourceCulture);
    public static string Progress_Cancelled => ResourceManager.GetString("Progress_Cancelled", resourceCulture);
    public static string Progress_Deploying => ResourceManager.GetString("Progress_Deploying", resourceCulture);

    // Profile Editor
    public static string Nav_ProfileEditor => ResourceManager.GetString("Nav_ProfileEditor", resourceCulture);
    public static string Editor_Title_New => ResourceManager.GetString("Editor_Title_New", resourceCulture);
    public static string Editor_Title_Edit => ResourceManager.GetString("Editor_Title_Edit", resourceCulture);
    public static string Editor_Lbl_Name => ResourceManager.GetString("Editor_Lbl_Name", resourceCulture);
    public static string Editor_Lbl_Parent => ResourceManager.GetString("Editor_Lbl_Parent", resourceCulture);
    public static string Editor_Lbl_Description => ResourceManager.GetString("Editor_Lbl_Description", resourceCulture);
    public static string Editor_Section_Inherited => ResourceManager.GetString("Editor_Section_Inherited", resourceCulture);
    public static string Editor_Section_Added => ResourceManager.GetString("Editor_Section_Added", resourceCulture);
    public static string Editor_NoParent => ResourceManager.GetString("Editor_NoParent", resourceCulture);
    public static string Editor_Empty_NoParent => ResourceManager.GetString("Editor_Empty_NoParent", resourceCulture);
    public static string Editor_Empty_NoApps => ResourceManager.GetString("Editor_Empty_NoApps", resourceCulture);
    public static string Editor_Tooltip_Inherited => ResourceManager.GetString("Editor_Tooltip_Inherited", resourceCulture);
    public static string Editor_Tooltip_Add => ResourceManager.GetString("Editor_Tooltip_Add", resourceCulture);
    public static string Editor_Tooltip_Remove => ResourceManager.GetString("Editor_Tooltip_Remove", resourceCulture);
    public static string Editor_Error_NameRequired => ResourceManager.GetString("Editor_Error_NameRequired", resourceCulture);
    public static string Editor_Error_LoadParent => ResourceManager.GetString("Editor_Error_LoadParent", resourceCulture);
    public static string Editor_Error_InvalidName => ResourceManager.GetString("Editor_Error_InvalidName", resourceCulture);
    public static string Editor_Error_SaveFailed => ResourceManager.GetString("Editor_Error_SaveFailed", resourceCulture);
    public static string Editor_Hint_ProfileName => ResourceManager.GetString("Editor_Hint_ProfileName", resourceCulture);
    public static string Editor_Hint_Description => ResourceManager.GetString("Editor_Hint_Description", resourceCulture);
    public static string Btn_Save => ResourceManager.GetString("Btn_Save", resourceCulture);
    public static string Msg_ProfileSaved => ResourceManager.GetString("Msg_ProfileSaved", resourceCulture);

    // Application Picker Dialog
    public static string Dialog_SelectApp_Title => ResourceManager.GetString("Dialog_SelectApp_Title", resourceCulture);
    public static string Dialog_SelectApp_Add => ResourceManager.GetString("Dialog_SelectApp_Add", resourceCulture);
    public static string Dialog_NoAppsAvailable => ResourceManager.GetString("Dialog_NoAppsAvailable", resourceCulture);
    public static string Dialog_AppsAvailable => ResourceManager.GetString("Dialog_AppsAvailable", resourceCulture);

    // Dashboard - Extended
    public static string Dashboard_Refresh => ResourceManager.GetString("Dashboard_Refresh", resourceCulture);
    public static string Dashboard_Stat_Profiles => ResourceManager.GetString("Dashboard_Stat_Profiles", resourceCulture);
    public static string Dashboard_Stat_Apps => ResourceManager.GetString("Dashboard_Stat_Apps", resourceCulture);
    public static string Dashboard_Stat_Deployments => ResourceManager.GetString("Dashboard_Stat_Deployments", resourceCulture);
    public static string Dashboard_Stat_Version => ResourceManager.GetString("Dashboard_Stat_Version", resourceCulture);
    public static string Dashboard_Sys_Hostname => ResourceManager.GetString("Dashboard_Sys_Hostname", resourceCulture);
    public static string Dashboard_Sys_OS => ResourceManager.GetString("Dashboard_Sys_OS", resourceCulture);
    public static string Dashboard_Sys_Build => ResourceManager.GetString("Dashboard_Sys_Build", resourceCulture);
    public static string Dashboard_Sys_Admin => ResourceManager.GetString("Dashboard_Sys_Admin", resourceCulture);
    public static string Dashboard_RecentActivity => ResourceManager.GetString("Dashboard_RecentActivity", resourceCulture);
    public static string Dashboard_NoActivity => ResourceManager.GetString("Dashboard_NoActivity", resourceCulture);
    public static string Dashboard_NoActivity_Hint => ResourceManager.GetString("Dashboard_NoActivity_Hint", resourceCulture);

    // Settings
    public static string Nav_Settings => ResourceManager.GetString("Nav_Settings", resourceCulture);
    public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture);
    public static string Settings_Section_Appearance => ResourceManager.GetString("Settings_Section_Appearance", resourceCulture);
    public static string Settings_Section_Language => ResourceManager.GetString("Settings_Section_Language", resourceCulture);
    public static string Settings_Section_Data => ResourceManager.GetString("Settings_Section_Data", resourceCulture);
    public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture);
    public static string Settings_Theme_Desc => ResourceManager.GetString("Settings_Theme_Desc", resourceCulture);
    public static string Settings_ThemeApplied => ResourceManager.GetString("Settings_ThemeApplied", resourceCulture);
    public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture);
    public static string Settings_Language_Desc => ResourceManager.GetString("Settings_Language_Desc", resourceCulture);
    public static string Settings_Apply => ResourceManager.GetString("Settings_Apply", resourceCulture);
    public static string Settings_RestartRequired => ResourceManager.GetString("Settings_RestartRequired", resourceCulture);
    public static string Settings_ClearHistory => ResourceManager.GetString("Settings_ClearHistory", resourceCulture);
    public static string Settings_ClearHistory_Desc => ResourceManager.GetString("Settings_ClearHistory_Desc", resourceCulture);
    public static string Settings_ClearBtn => ResourceManager.GetString("Settings_ClearBtn", resourceCulture);
    public static string Settings_HistoryCleared => ResourceManager.GetString("Settings_HistoryCleared", resourceCulture);

    // Package Managers
    public static string Dashboard_Sys_Winget => ResourceManager.GetString("Dashboard_Sys_Winget", resourceCulture);
    public static string Dashboard_Sys_Chocolatey => ResourceManager.GetString("Dashboard_Sys_Chocolatey", resourceCulture);

    // Apps Manager - Extended
    public static string Apps_Installed => ResourceManager.GetString("Apps_Installed", resourceCulture);
    public static string Apps_Selected => ResourceManager.GetString("Apps_Selected", resourceCulture);
    public static string Apps_InstallSelected => ResourceManager.GetString("Apps_InstallSelected", resourceCulture);
    public static string Apps_SelectAll => ResourceManager.GetString("Apps_SelectAll", resourceCulture);
    public static string Apps_SelectNone => ResourceManager.GetString("Apps_SelectNone", resourceCulture);
    public static string Apps_SelectNotInstalled => ResourceManager.GetString("Apps_SelectNotInstalled", resourceCulture);
    public static string Apps_StatusAll => ResourceManager.GetString("Apps_StatusAll", resourceCulture);
    public static string Apps_StatusInstalled => ResourceManager.GetString("Apps_StatusInstalled", resourceCulture);
    public static string Apps_StatusNotInstalled => ResourceManager.GetString("Apps_StatusNotInstalled", resourceCulture);
    public static string Apps_StatusSelected => ResourceManager.GetString("Apps_StatusSelected", resourceCulture);
    public static string Apps_ManualInstall => ResourceManager.GetString("Apps_ManualInstall", resourceCulture);
    public static string Apps_ManualInstallTooltip => ResourceManager.GetString("Apps_ManualInstallTooltip", resourceCulture);
    public static string Apps_OpenWebsite => ResourceManager.GetString("Apps_OpenWebsite", resourceCulture);
    public static string Status_ManualRequired => ResourceManager.GetString("Status_ManualRequired", resourceCulture);

    // Context Menu
    public static string Menu_OpenHomepage => ResourceManager.GetString("Menu_OpenHomepage", resourceCulture);
    public static string Menu_Install => ResourceManager.GetString("Menu_Install", resourceCulture);
    public static string Menu_ViewLogs => ResourceManager.GetString("Menu_ViewLogs", resourceCulture);
    public static string Menu_ToggleSelection => ResourceManager.GetString("Menu_ToggleSelection", resourceCulture);
    public static string Menu_CopyAppId => ResourceManager.GetString("Menu_CopyAppId", resourceCulture);
    public static string Menu_CopyWingetId => ResourceManager.GetString("Menu_CopyWingetId", resourceCulture);
    public static string Menu_Uninstall => ResourceManager.GetString("Menu_Uninstall", resourceCulture);

    // Status Messages - Uninstall
    public static string Status_Uninstalling => ResourceManager.GetString("Status_Uninstalling", resourceCulture);
    public static string Status_Uninstalled => ResourceManager.GetString("Status_Uninstalled", resourceCulture);

    // Error Messages
    public static string Common_ErrorFallback => ResourceManager.GetString("Common_ErrorFallback", resourceCulture);

    // Prerequisites
    public static string Prerequisites_Title => ResourceManager.GetString("Prerequisites_Title", resourceCulture);
    public static string Prerequisites_AllInstalled => ResourceManager.GetString("Prerequisites_AllInstalled", resourceCulture);
    public static string Prerequisites_MissingCount => ResourceManager.GetString("Prerequisites_MissingCount", resourceCulture);
    public static string Prerequisites_Install => ResourceManager.GetString("Prerequisites_Install", resourceCulture);
    public static string Prerequisites_Check => ResourceManager.GetString("Prerequisites_Check", resourceCulture);
    public static string Prerequisites_Starting => ResourceManager.GetString("Prerequisites_Starting", resourceCulture);
    public static string Prerequisites_LoadingModules => ResourceManager.GetString("Prerequisites_LoadingModules", resourceCulture);
    public static string Prerequisites_Installing => ResourceManager.GetString("Prerequisites_Installing", resourceCulture);
    public static string Prerequisites_Complete => ResourceManager.GetString("Prerequisites_Complete", resourceCulture);
    public static string Prerequisites_PowerShell7 => ResourceManager.GetString("Prerequisites_PowerShell7", resourceCulture);
    public static string Prerequisites_Winget => ResourceManager.GetString("Prerequisites_Winget", resourceCulture);
    public static string Prerequisites_Chocolatey => ResourceManager.GetString("Prerequisites_Chocolatey", resourceCulture);

    // Favorites
    public static string Apps_StatusFavorites => ResourceManager.GetString("Apps_StatusFavorites", resourceCulture);
    public static string Menu_ToggleFavorite => ResourceManager.GetString("Menu_ToggleFavorite", resourceCulture);
    public static string Apps_SelectFavorites => ResourceManager.GetString("Apps_SelectFavorites", resourceCulture);
    public static string Apps_Favorites => ResourceManager.GetString("Apps_Favorites", resourceCulture);

    // Batch Operations
    public static string Apps_UninstallSelected => ResourceManager.GetString("Apps_UninstallSelected", resourceCulture);
    public static string Btn_CancelBatch => ResourceManager.GetString("Btn_CancelBatch", resourceCulture);
    public static string Progress_BatchProgress => ResourceManager.GetString("Progress_BatchProgress", resourceCulture);

    // Export/Import
    public static string Btn_ExportSelection => ResourceManager.GetString("Btn_ExportSelection", resourceCulture);
    public static string Btn_ImportSelection => ResourceManager.GetString("Btn_ImportSelection", resourceCulture);
    public static string Btn_ExportFavorites => ResourceManager.GetString("Btn_ExportFavorites", resourceCulture);
    public static string Btn_ImportFavorites => ResourceManager.GetString("Btn_ImportFavorites", resourceCulture);

    // Summary Dialog
    public static string Summary_Title => ResourceManager.GetString("Summary_Title", resourceCulture);
    public static string Summary_Success => ResourceManager.GetString("Summary_Success", resourceCulture);
    public static string Summary_PartialSuccess => ResourceManager.GetString("Summary_PartialSuccess", resourceCulture);
    public static string Summary_Failed => ResourceManager.GetString("Summary_Failed", resourceCulture);
    public static string Summary_Cancelled => ResourceManager.GetString("Summary_Cancelled", resourceCulture);
    public static string Summary_Successful => ResourceManager.GetString("Summary_Successful", resourceCulture);
    public static string Summary_FailedCount => ResourceManager.GetString("Summary_FailedCount", resourceCulture);
    public static string Summary_SkippedCount => ResourceManager.GetString("Summary_SkippedCount", resourceCulture);
    public static string Summary_Close => ResourceManager.GetString("Summary_Close", resourceCulture);

    // Statistics
    public static string Apps_Stats_Total => ResourceManager.GetString("Apps_Stats_Total", resourceCulture);
    public static string Apps_Stats_Installed => ResourceManager.GetString("Apps_Stats_Installed", resourceCulture);
    public static string Apps_Stats_Selected => ResourceManager.GetString("Apps_Stats_Selected", resourceCulture);
    public static string Apps_Stats_Favorites => ResourceManager.GetString("Apps_Stats_Favorites", resourceCulture);

    // Performance Settings
    public static string Settings_ParallelInstalls => ResourceManager.GetString("Settings_ParallelInstalls", resourceCulture);
    public static string Settings_ParallelInstalls_Desc => ResourceManager.GetString("Settings_ParallelInstalls_Desc", resourceCulture);
    public static string Settings_ParallelInstallsApplied => ResourceManager.GetString("Settings_ParallelInstallsApplied", resourceCulture);
    public static string Settings_ParallelScans => ResourceManager.GetString("Settings_ParallelScans", resourceCulture);
    public static string Settings_ParallelScans_Desc => ResourceManager.GetString("Settings_ParallelScans_Desc", resourceCulture);
    public static string Settings_ParallelScansApplied => ResourceManager.GetString("Settings_ParallelScansApplied", resourceCulture);
    public static string Settings_Section_Performance => ResourceManager.GetString("Settings_Section_Performance", resourceCulture);

    // Dialog System
    public static string Dialog_Error_Title => ResourceManager.GetString("Dialog_Error_Title", resourceCulture);
    public static string Dialog_Error_Details => ResourceManager.GetString("Dialog_Error_Details", resourceCulture);
    public static string Dialog_OK => ResourceManager.GetString("Dialog_OK", resourceCulture);
    public static string Dialog_Cancel => ResourceManager.GetString("Dialog_Cancel", resourceCulture);
    public static string Dialog_Retry => ResourceManager.GetString("Dialog_Retry", resourceCulture);
    public static string Dialog_Help => ResourceManager.GetString("Dialog_Help", resourceCulture);
    public static string Dialog_Close => ResourceManager.GetString("Dialog_Close", resourceCulture);
    public static string Dialog_Confirm => ResourceManager.GetString("Dialog_Confirm", resourceCulture);

    // Keyboard Shortcuts Help
    public static string Help_KeyboardShortcuts => ResourceManager.GetString("Help_KeyboardShortcuts", resourceCulture);
    public static string Help_Section_General => ResourceManager.GetString("Help_Section_General", resourceCulture);
    public static string Help_Section_AppManager => ResourceManager.GetString("Help_Section_AppManager", resourceCulture);
    public static string Help_Section_Navigation => ResourceManager.GetString("Help_Section_Navigation", resourceCulture);
    public static string Help_Shortcut_Help => ResourceManager.GetString("Help_Shortcut_Help", resourceCulture);
    public static string Help_Shortcut_Refresh => ResourceManager.GetString("Help_Shortcut_Refresh", resourceCulture);
    public static string Help_Shortcut_Settings => ResourceManager.GetString("Help_Shortcut_Settings", resourceCulture);
    public static string Help_Shortcut_SelectAll => ResourceManager.GetString("Help_Shortcut_SelectAll", resourceCulture);
    public static string Help_Shortcut_ClearSelection => ResourceManager.GetString("Help_Shortcut_ClearSelection", resourceCulture);
    public static string Help_Shortcut_ToggleFavorite => ResourceManager.GetString("Help_Shortcut_ToggleFavorite", resourceCulture);
    public static string Help_Shortcut_Uninstall => ResourceManager.GetString("Help_Shortcut_Uninstall", resourceCulture);
    public static string Help_Shortcut_Install => ResourceManager.GetString("Help_Shortcut_Install", resourceCulture);
    public static string Help_Shortcut_ToggleSelect => ResourceManager.GetString("Help_Shortcut_ToggleSelect", resourceCulture);
    public static string Help_Shortcut_Dashboard => ResourceManager.GetString("Help_Shortcut_Dashboard", resourceCulture);
    public static string Help_Shortcut_Prerequisites => ResourceManager.GetString("Help_Shortcut_Prerequisites", resourceCulture);
    public static string Help_Shortcut_Apps => ResourceManager.GetString("Help_Shortcut_Apps", resourceCulture);
    public static string Help_Shortcut_Deployment => ResourceManager.GetString("Help_Shortcut_Deployment", resourceCulture);
    public static string Help_Shortcut_ProfileEditor => ResourceManager.GetString("Help_Shortcut_ProfileEditor", resourceCulture);

    // Onboarding
    public static string Onboarding_Welcome => ResourceManager.GetString("Onboarding_Welcome", resourceCulture);
    public static string Onboarding_Subtitle => ResourceManager.GetString("Onboarding_Subtitle", resourceCulture);
    public static string Onboarding_Step1_Title => ResourceManager.GetString("Onboarding_Step1_Title", resourceCulture);
    public static string Onboarding_Step1_Desc => ResourceManager.GetString("Onboarding_Step1_Desc", resourceCulture);
    public static string Onboarding_Step2_Title => ResourceManager.GetString("Onboarding_Step2_Title", resourceCulture);
    public static string Onboarding_Step2_Desc => ResourceManager.GetString("Onboarding_Step2_Desc", resourceCulture);
    public static string Onboarding_Step3_Title => ResourceManager.GetString("Onboarding_Step3_Title", resourceCulture);
    public static string Onboarding_Step3_Desc => ResourceManager.GetString("Onboarding_Step3_Desc", resourceCulture);
    public static string Onboarding_Tip => ResourceManager.GetString("Onboarding_Tip", resourceCulture);
    public static string Onboarding_Tip_Shortcuts => ResourceManager.GetString("Onboarding_Tip_Shortcuts", resourceCulture);
    public static string Onboarding_DontShowAgain => ResourceManager.GetString("Onboarding_DontShowAgain", resourceCulture);
    public static string Onboarding_GetStarted => ResourceManager.GetString("Onboarding_GetStarted", resourceCulture);

    // Progress Time Estimates
    public static string Progress_TimeRemaining => ResourceManager.GetString("Progress_TimeRemaining", resourceCulture);
    public static string Progress_TimeMinutes => ResourceManager.GetString("Progress_TimeMinutes", resourceCulture);
    public static string Progress_TimeSeconds => ResourceManager.GetString("Progress_TimeSeconds", resourceCulture);
    public static string Progress_Calculating => ResourceManager.GetString("Progress_Calculating", resourceCulture);

    // Toast Notifications
    public static string Toast_InstallComplete => ResourceManager.GetString("Toast_InstallComplete", resourceCulture);
    public static string Toast_UninstallComplete => ResourceManager.GetString("Toast_UninstallComplete", resourceCulture);
    public static string Toast_ScanComplete => ResourceManager.GetString("Toast_ScanComplete", resourceCulture);
    public static string Toast_ProfileSaved => ResourceManager.GetString("Toast_ProfileSaved", resourceCulture);
    public static string Toast_ExportComplete => ResourceManager.GetString("Toast_ExportComplete", resourceCulture);
    public static string Toast_ImportComplete => ResourceManager.GetString("Toast_ImportComplete", resourceCulture);
    public static string Toast_ViewDetails => ResourceManager.GetString("Toast_ViewDetails", resourceCulture);

    // Form Validation
    public static string Validation_Required => ResourceManager.GetString("Validation_Required", resourceCulture);
    public static string Validation_InvalidChars => ResourceManager.GetString("Validation_InvalidChars", resourceCulture);
    public static string Validation_TooLong => ResourceManager.GetString("Validation_TooLong", resourceCulture);
    public static string Validation_AlreadyExists => ResourceManager.GetString("Validation_AlreadyExists", resourceCulture);

    // Help System Tooltips
    public static string Help_Tooltip_Scan => ResourceManager.GetString("Help_Tooltip_Scan", resourceCulture);
    public static string Help_Tooltip_Install => ResourceManager.GetString("Help_Tooltip_Install", resourceCulture);
    public static string Help_Tooltip_Deploy => ResourceManager.GetString("Help_Tooltip_Deploy", resourceCulture);
    public static string Help_Tooltip_DryRun => ResourceManager.GetString("Help_Tooltip_DryRun", resourceCulture);

    // Contextual Help
    public static string Help_SelectProfile => ResourceManager.GetString("Help_SelectProfile", resourceCulture);
    public static string Help_DryRun => ResourceManager.GetString("Help_DryRun", resourceCulture);
    public static string Help_Performance => ResourceManager.GetString("Help_Performance", resourceCulture);

    // Confirmation Dialogs
    public static string Confirm_ClearHistory_Title => ResourceManager.GetString("Confirm_ClearHistory_Title", resourceCulture);
    public static string Confirm_ClearHistory_Message => ResourceManager.GetString("Confirm_ClearHistory_Message", resourceCulture);
    public static string Confirm_Uninstall_Title => ResourceManager.GetString("Confirm_Uninstall_Title", resourceCulture);
    public static string Confirm_Uninstall_Message => ResourceManager.GetString("Confirm_Uninstall_Message", resourceCulture);
    public static string Confirm_DeleteProfile_Title => ResourceManager.GetString("Confirm_DeleteProfile_Title", resourceCulture);
    public static string Confirm_DeleteProfile_Message => ResourceManager.GetString("Confirm_DeleteProfile_Message", resourceCulture);
    public static string Confirm_Yes => ResourceManager.GetString("Confirm_Yes", resourceCulture);
    public static string Confirm_No => ResourceManager.GetString("Confirm_No", resourceCulture);

    // Profile Export/Import
    public static string Editor_Btn_Export => ResourceManager.GetString("Editor_Btn_Export", resourceCulture);
    public static string Editor_Btn_Import => ResourceManager.GetString("Editor_Btn_Import", resourceCulture);
    public static string Export_FileFilter => ResourceManager.GetString("Export_FileFilter", resourceCulture);
    public static string Import_FileFilter => ResourceManager.GetString("Import_FileFilter", resourceCulture);
    public static string Export_Success => ResourceManager.GetString("Export_Success", resourceCulture);
    public static string Import_Success => ResourceManager.GetString("Import_Success", resourceCulture);
    public static string Import_Error_Invalid => ResourceManager.GetString("Import_Error_Invalid", resourceCulture);
    public static string Import_Error_Validation => ResourceManager.GetString("Import_Error_Validation", resourceCulture);

    // Application Updates
    public static string Btn_ScanUpdates => ResourceManager.GetString("Btn_ScanUpdates", resourceCulture);
    public static string Btn_Update => ResourceManager.GetString("Btn_Update", resourceCulture);
    public static string Btn_UpdateSelected => ResourceManager.GetString("Btn_UpdateSelected", resourceCulture);
    public static string Menu_Update => ResourceManager.GetString("Menu_Update", resourceCulture);
    public static string Menu_Launch => ResourceManager.GetString("Menu_Launch", resourceCulture);
    public static string Error_LaunchFailed => ResourceManager.GetString("Error_LaunchFailed", resourceCulture);
    public static string Status_UpdateAvailable => ResourceManager.GetString("Status_UpdateAvailable", resourceCulture);
    public static string Status_Updating => ResourceManager.GetString("Status_Updating", resourceCulture);
    public static string Apps_StatusHasUpdates => ResourceManager.GetString("Apps_StatusHasUpdates", resourceCulture);
    public static string Apps_SelectWithUpdates => ResourceManager.GetString("Apps_SelectWithUpdates", resourceCulture);
    public static string Col_AvailableVersion => ResourceManager.GetString("Col_AvailableVersion", resourceCulture);
    public static string Col_Version => ResourceManager.GetString("Col_Version", resourceCulture);
    public static string Toast_UpdatesFound => ResourceManager.GetString("Toast_UpdatesFound", resourceCulture);
    public static string Apps_NoUpdates => ResourceManager.GetString("Apps_NoUpdates", resourceCulture);

    // Navigation - Extended
    public static string Nav_Back => ResourceManager.GetString("Nav_Back", resourceCulture);

    // Settings Tabs
    public static string Settings_Tab_Appearance => ResourceManager.GetString("Settings_Tab_Appearance", resourceCulture);
    public static string Settings_Tab_Performance => ResourceManager.GetString("Settings_Tab_Performance", resourceCulture);
    public static string Settings_Tab_Data => ResourceManager.GetString("Settings_Tab_Data", resourceCulture);
    public static string Settings_Tab_About => ResourceManager.GetString("Settings_Tab_About", resourceCulture);
    public static string Settings_Section_About => ResourceManager.GetString("Settings_Section_About", resourceCulture);

    // Accessibility
    public static string Settings_ReducedMotion => ResourceManager.GetString("Settings_ReducedMotion", resourceCulture);
    public static string Settings_ReducedMotion_Desc => ResourceManager.GetString("Settings_ReducedMotion_Desc", resourceCulture);

    // Settings Export/Import
    public static string Settings_Export => ResourceManager.GetString("Settings_Export", resourceCulture);
    public static string Settings_Export_Desc => ResourceManager.GetString("Settings_Export_Desc", resourceCulture);
    public static string Settings_ExportSuccess => ResourceManager.GetString("Settings_ExportSuccess", resourceCulture);
    public static string Settings_ExportFailed => ResourceManager.GetString("Settings_ExportFailed", resourceCulture);
    public static string Settings_Import => ResourceManager.GetString("Settings_Import", resourceCulture);
    public static string Settings_Import_Desc => ResourceManager.GetString("Settings_Import_Desc", resourceCulture);
    public static string Settings_ImportSuccess => ResourceManager.GetString("Settings_ImportSuccess", resourceCulture);
    public static string Settings_ImportFailed => ResourceManager.GetString("Settings_ImportFailed", resourceCulture);

    // Settings Reset
    public static string Settings_Reset => ResourceManager.GetString("Settings_Reset", resourceCulture);
    public static string Settings_Reset_Desc => ResourceManager.GetString("Settings_Reset_Desc", resourceCulture);
    public static string Confirm_ResetSettings_Title => ResourceManager.GetString("Confirm_ResetSettings_Title", resourceCulture);
    public static string Confirm_ResetSettings_Message => ResourceManager.GetString("Confirm_ResetSettings_Message", resourceCulture);
    public static string Settings_ResetSuccess => ResourceManager.GetString("Settings_ResetSuccess", resourceCulture);
    public static string Settings_ResetFailed => ResourceManager.GetString("Settings_ResetFailed", resourceCulture);

    // Logs
    public static string Settings_OpenLogs => ResourceManager.GetString("Settings_OpenLogs", resourceCulture);
    public static string Settings_OpenLogs_Desc => ResourceManager.GetString("Settings_OpenLogs_Desc", resourceCulture);
    public static string Logs_Loading => ResourceManager.GetString("Logs_Loading", resourceCulture);
    public static string Confirm_ClearOldLogs_Title => ResourceManager.GetString("Confirm_ClearOldLogs_Title", resourceCulture);
    public static string Confirm_ClearOldLogs_Message => ResourceManager.GetString("Confirm_ClearOldLogs_Message", resourceCulture);

    // GitHub
    public static string Settings_OpenGitHub => ResourceManager.GetString("Settings_OpenGitHub", resourceCulture);
    public static string Settings_OpenGitHub_Desc => ResourceManager.GetString("Settings_OpenGitHub_Desc", resourceCulture);

    // Profile Selection
    public static string Apps_ProfileLabel => ResourceManager.GetString("Apps_ProfileLabel", resourceCulture);
    public static string Apps_SelectProfile => ResourceManager.GetString("Apps_SelectProfile", resourceCulture);
    public static string Apps_ClearProfile => ResourceManager.GetString("Apps_ClearProfile", resourceCulture);
    public static string Apps_AppsSelected => ResourceManager.GetString("Apps_AppsSelected", resourceCulture);

    // Save Profile Dialog
    public static string Apps_SaveProfile => ResourceManager.GetString("Apps_SaveProfile", resourceCulture);

    // Monitoring
    public static string Monitoring_Title => ResourceManager.GetString("Monitoring_Title", resourceCulture);
    public static string Monitoring_Subtitle => ResourceManager.GetString("Monitoring_Subtitle", resourceCulture);
    public static string Monitoring_NoDeployment => ResourceManager.GetString("Monitoring_NoDeployment", resourceCulture);
    public static string Monitoring_NoDeploymentHint => ResourceManager.GetString("Monitoring_NoDeploymentHint", resourceCulture);
    public static string Dialog_SaveProfile_Title => ResourceManager.GetString("Dialog_SaveProfile_Title", resourceCulture);
    public static string Dialog_SaveProfile_AppsSelected => ResourceManager.GetString("Dialog_SaveProfile_AppsSelected", resourceCulture);
    public static string Dialog_SaveProfile_Overwrite => ResourceManager.GetString("Dialog_SaveProfile_Overwrite", resourceCulture);
    public static string Dialog_SaveProfile_CreateNew => ResourceManager.GetString("Dialog_SaveProfile_CreateNew", resourceCulture);
    public static string Dialog_SaveProfile_Success => ResourceManager.GetString("Dialog_SaveProfile_Success", resourceCulture);
    public static string Dialog_SaveProfile_Error => ResourceManager.GetString("Dialog_SaveProfile_Error", resourceCulture);
    public static string Dialog_SaveProfile_NoApps => ResourceManager.GetString("Dialog_SaveProfile_NoApps", resourceCulture);

    // Dashboard - Hero Section (Action-First Design)
    public static string Dashboard_Hero_Checking => ResourceManager.GetString("Dashboard_Hero_Checking", resourceCulture);
    public static string Dashboard_Hero_Ready => ResourceManager.GetString("Dashboard_Hero_Ready", resourceCulture);
    public static string Dashboard_Hero_NeedPrereqs => ResourceManager.GetString("Dashboard_Hero_NeedPrereqs", resourceCulture);
    public static string Dashboard_Hero_HasUpdates => ResourceManager.GetString("Dashboard_Hero_HasUpdates", resourceCulture);
    public static string Dashboard_Btn_StartDeployment => ResourceManager.GetString("Dashboard_Btn_StartDeployment", resourceCulture);
    public static string Dashboard_Btn_FixPrereqs => ResourceManager.GetString("Dashboard_Btn_FixPrereqs", resourceCulture);
    public static string Dashboard_Btn_ViewUpdates => ResourceManager.GetString("Dashboard_Btn_ViewUpdates", resourceCulture);
    public static string Dashboard_Stats_Profiles => ResourceManager.GetString("Dashboard_Stats_Profiles", resourceCulture);
    public static string Dashboard_Stats_Apps => ResourceManager.GetString("Dashboard_Stats_Apps", resourceCulture);
    public static string Dashboard_Stats_Updates => ResourceManager.GetString("Dashboard_Stats_Updates", resourceCulture);
    public static string Dashboard_History_Title => ResourceManager.GetString("Dashboard_History_Title", resourceCulture);
    public static string Dashboard_History_Empty => ResourceManager.GetString("Dashboard_History_Empty", resourceCulture);

    // Dashboard - Phase Indicators
    public static string Dashboard_Phase_LoadingInfo => ResourceManager.GetString("Dashboard_Phase_LoadingInfo", resourceCulture);
    public static string Dashboard_Phase_CheckingPrereqs => ResourceManager.GetString("Dashboard_Phase_CheckingPrereqs", resourceCulture);
    public static string Dashboard_Phase_ScanningUpdates => ResourceManager.GetString("Dashboard_Phase_ScanningUpdates", resourceCulture);

    // Dashboard - Last Check Timestamps
    public static string Dashboard_LastCheck_JustNow => ResourceManager.GetString("Dashboard_LastCheck_JustNow", resourceCulture);
    public static string Dashboard_LastCheck_MinutesAgo => ResourceManager.GetString("Dashboard_LastCheck_MinutesAgo", resourceCulture);
    public static string Dashboard_LastCheck_HoursAgo => ResourceManager.GetString("Dashboard_LastCheck_HoursAgo", resourceCulture);

    // Dashboard - Stat Card Hints
    public static string Dashboard_Stats_ProfilesHint => ResourceManager.GetString("Dashboard_Stats_ProfilesHint", resourceCulture);
    public static string Dashboard_Stats_AppsHint => ResourceManager.GetString("Dashboard_Stats_AppsHint", resourceCulture);
    public static string Dashboard_Stats_UpdatesHint => ResourceManager.GetString("Dashboard_Stats_UpdatesHint", resourceCulture);

    // Dashboard - Hero Subtitles
    public static string Dashboard_Hero_Subtitle_Ready => ResourceManager.GetString("Dashboard_Hero_Subtitle_Ready", resourceCulture);
    public static string Dashboard_Hero_Subtitle_Prereqs => ResourceManager.GetString("Dashboard_Hero_Subtitle_Prereqs", resourceCulture);
    public static string Dashboard_Hero_Subtitle_Updates => ResourceManager.GetString("Dashboard_Hero_Subtitle_Updates", resourceCulture);

    // Dashboard - Scan
    public static string Dashboard_Scan_Button => ResourceManager.GetString("Dashboard_Scan_Button", resourceCulture);
    public static string Dashboard_Scan_Progress => ResourceManager.GetString("Dashboard_Scan_Progress", resourceCulture);

    // Error Recovery Suggestions
    public static string Recovery_CheckInternet => ResourceManager.GetString("Recovery_CheckInternet", resourceCulture);
    public static string Recovery_CheckFirewall => ResourceManager.GetString("Recovery_CheckFirewall", resourceCulture);
    public static string Recovery_TryAgainLater => ResourceManager.GetString("Recovery_TryAgainLater", resourceCulture);
    public static string Recovery_RunAsAdmin => ResourceManager.GetString("Recovery_RunAsAdmin", resourceCulture);
    public static string Recovery_CheckPermissions => ResourceManager.GetString("Recovery_CheckPermissions", resourceCulture);
    public static string Recovery_CheckPath => ResourceManager.GetString("Recovery_CheckPath", resourceCulture);
    public static string Recovery_ReinstallApp => ResourceManager.GetString("Recovery_ReinstallApp", resourceCulture);
    public static string Recovery_CheckPrerequisites => ResourceManager.GetString("Recovery_CheckPrerequisites", resourceCulture);
    public static string Recovery_RetryInstall => ResourceManager.GetString("Recovery_RetryInstall", resourceCulture);
    public static string Recovery_ManualInstall => ResourceManager.GetString("Recovery_ManualInstall", resourceCulture);
    public static string Recovery_CheckPowerShell => ResourceManager.GetString("Recovery_CheckPowerShell", resourceCulture);
    public static string Recovery_UpdatePowerShell => ResourceManager.GetString("Recovery_UpdatePowerShell", resourceCulture);
    public static string Recovery_Generic_Retry => ResourceManager.GetString("Recovery_Generic_Retry", resourceCulture);
    public static string Recovery_Generic_Restart => ResourceManager.GetString("Recovery_Generic_Restart", resourceCulture);
    public static string Recovery_Generic_CheckLogs => ResourceManager.GetString("Recovery_Generic_CheckLogs", resourceCulture);
}
